### PR TITLE
fix: The target websocket watch the specific url instead of upstream(…

### PR DESCRIPTION
**Pull request by Dokki**
Quick fix for https://github.com/fastify/fastify-http-proxy/pull/304

Hello guys, I slightly redid the processing of wsUpstream property, I didn't take into account one point that would be better to fix for ease of use. I'm sorry, my bad.

The problem is that the target.pathname is lost if wsUpstream is have it.

Curently I was return the code on 159 line and add above new condition for wsUpstream property.
Now the code is more consistent and correct.

#### Checklist

- [ x ] run `npm run test`
- [  ] tests and/or benchmarks are included (Not needed)
- [  ] documentation is changed or added (Not needed)
- [ x ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
can you add a test to cover for the fix?

**Comment by Dokki** [comment]
@mcollina all covered.
image

**Comment by Dokki** [comment]
@mcollina test was adapted.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
