### PR TITLE
Add a peer dependency on `fastify` to fix TypeScript types

### PR DESCRIPTION
**Pull request by walkerburgin**
The TypeScript typings in `types/index.d.ts` import explicitly from `fastify` without this package taking a dependency on `fastify`. If consumers are using a strict package manager like PNPM or Yarn (Berry), the typings are currently broken. This PR adds a peer dependency on `fastify` to fix TypeScript typings. 

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — COMMENTED** [review]
Thank you, but peer dependencies cause too many problems. As an org, we avoid them.

**Comment by walkerburgin** [comment]
Mechanically, anything that ensures that `fastify` is installed and visible from the install location of `@fastify/http-proxy` will fix the issue that I'm encountering. I think a peer dependency (or even an optional peer dependency) is the pedantically correct choice, but moving `fastify` from a `devDependency` to a `dependency` would work as well. Would you be open to that instead?

**Comment by jsumners** [comment]
I don't know what the issue is or how to solve it. That'd be down to the @fastify/typescript folks. I just know that peer dependencies cause more headaches than they solve.

**Comment by mcollina** [comment]
@walkerburgin can you assemble an reproduction of this problem? Because I'm not seeing it in my codebase: pnpm creates a directory structure that resolves this correctly.

**Comment by walkerburgin** [comment]
Here's a repro: https://github.com/walkerburgin/fastify-http-proxy-repro. It turns out there's a similar issue with `@types/ws` as well.

The error repros when you set [`hoist = false`](https://pnpm.io/npmrc#hoist), which configures PNPM to be strict and require that all dependencies be fully declared. That type of strict correctness is valuable in scaling very large monorepos (see [here](https://docs.aspect.build/rulesets/aspect_rules_js/docs/pnpm/#hoisting) for example). I haven't tried, but I expect that we could repro the issue with Yarn's PnP as well.

**Comment by mcollina** [comment]
Unfortunately `peerDependencies` cause more problems that they are worth (especially with such a wild range of versions of npm, yarn, pnpm etc). We tend to follow the "standard behavior" of npm as much as possible.

Setting `hoist = false` is actually self-inflicted problems.

I'm closing this for now.

**Pull request closed without merging**
