### PR TITLE
chore(types): add internalRewriteLocationHeader in ts types

### PR DESCRIPTION
**Pull request by Xa3lis**
Hello,

The `internalRewriteLocationHeader` was added some months ago, it's working fine but the TS types had not been updated, so this is a quick PR to add it

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
looks good, but can you add a simple typing test please?

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Uzlopak — APPROVED** [review]
LGTM

**Comment by Uzlopak** [comment]
@fastify/leads 

Time for a release :)?

**Pull request merged**
