### PR TITLE
fix: prefix not getting replaced in certain cases

### LINKED ISSUE #152: fastify-http-proxy not removing prefix
## 🐛 Bug Report

When using fastify-http-proxy, the library does not remove the prefix from the request URL before proxying it to the upstream.

## To Reproduce

```js
fastify.register(require('fastify-http-proxy'), {
    upstream: 'example.com',
    prefix: 'testprefix'
 });

fastify.listen(3005, '0.0.0.0', function (err, address) {
    if (err) {
        fastify.log.error(err)
        process.exit(1)
    }
    fastify.log.info(`server listening on ${address}`)
});
```

For the request `/testprefix/users`, the upstream receives `/testprefix/users` instead of `/users`.

## Expected behavior

The prefix should be removed from the URL before proxying it to the upstream.

## Your Environment

- *node version*: 14
- *fastify version*: >=3.14.2
- *os*: Windows

### PR DESCRIPTION
**Pull request by BlazingAsher**
Fixes #152 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by BlazingAsher** [comment]
To be honest, I'm not sure what to even test for. It seems to work with `this` in certain projects but requires the change in others.

**Comment by mcollina** [comment]
What was the bug? Have you got a reproduction that you used to check if this fixed your problem? Port that to be a unit test.

**Comment by BlazingAsher** [comment]
The bug was that the prefix was not getting replaced before the request is forwarded to upstream.

I have been using this library without issue in another project, but a new one that I just created following the example in the README wasn't working.

I'll take a closer look to see if there are any differences, but the implementation in the units tests look to be the same as the one I am using.

**Comment by mcollina** [comment]
There is likely _some_ difference ;).

**Comment by BlazingAsher** [comment]
Okay, it seems that my TypeScript watcher stopped working so I was running an older version during my testing. The issue is caused by the fastify-websocket library. It hijacks the handlers and binds the internal fastify server object instead of the public API.

Let me know how you'd like me to proceed with this, since I don't think this is normal behaviour and you may not want to deal with it, but I am happy to write a test if you'd like to incorporate this change.

**Comment by mcollina** [comment]
Does the fix resolve your problem then?

**Comment by BlazingAsher** [comment]
Yes, the proposed changes fixes it.

**Comment by mcollina** [comment]
Then add an automated test that failed before the change.

**Review by mcollina — COMMENTED** [review]
Now that I see the fix, I'm starting to think I might be wrong and the bug might actually be in fastify-websocket.

What do you think?

**Comment by BlazingAsher** [comment]
Yeah, that's what I'm thinking, so I'm not too sure what you want to do with it. The change does fix the problem and it seems there is already use of `fastify.prefix` instead of `this.prefix` anyways, but I'm not sure whether you want to test for something that isn't really supposed to happen in the first place.

**Comment by mcollina** [comment]
Take a look at https://github.com/fastify/fastify-websocket/pull/122, I think it's the correct fix.

**Pull request closed without merging**
