### PR TITLE
feat: add default and named export

### PR DESCRIPTION
**Pull request by climba03003**
Fixes: #169 
add `default` and `named` export.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by climba03003** [comment]
@mcollina should we consider this as `minor` or `patch`? both are suitable in my mind. 
It fix the export and TypeScript mismatch problem. 
It also provide more support on different import style.

**Comment by mcollina** [comment]
patch is totally ok! Could you do the honors?

**Comment by climba03003** [comment]
> 
> 
> patch is totally ok! Could you do the honors?

Sure, I will release it as `patch`

**Pull request merged**
